defaultCheckUrl: http://api.m.jd.com
changeRequest:
  - hostRegex: .+\.jd\.com
    proxy: proxy
upstream:
  proxy:
    template: '{{$x := regexFindAll "\\d{1,3}(\\.\\d{1,3}){3}:\\d{2,5}" . -1}}{{range $s := $x}}{{printf "http://%s\n" $s}}{{end}}'
    apiUrl: xxx
    lifecycle: 25
    maxSize: 1
    requestInterval: 1000ms
